---
- name: Install the ElasticSearch repository key
  shell: "wget -qO - https://packages.elasticsearch.org/GPG-KEY-elasticsearch | sudo apt-key add -"

- name: Enable the ElasticSearch repository
  apt_repository: repo="deb http://packages.elasticsearch.org/elasticsearch/1.4/debian stable main"
                  state=present

- name: Install ElasticSearch
  apt: pkg=elasticsearch state=installed update-cache=yes

- name: Configure ElasticSearch to run on bootup
  shell: "update-rc.d elasticsearch defaults 95 10"
  notify: restart elasticsearch
